### PR TITLE
Add unit tests for interpolate function

### PR DESCRIPTION
**Pull request by mlh758**
Fix string interpolation containing single quotes

Fix interpolation with multiple parameters

Fix a couple of linter issues in readme and stmt.go

I see there are also tests in driver_test.go but those seem to actually hit a database and I don't have a development database set up to run against.

### CODE REVIEW

**Comment by mlh758** [comment]
This actually isn't quite ready yet, my quote escape will turn `''` into `''''` which is about as bad as leaving single quotes unescaped.

**Comment by mlh758** [comment]
That's better, pairs quotes more accurately with a lot more test cases around that.

**Comment by mlh758** [comment]
Looks like a docker build is failing in CI? Doesn't _look_ related to my change, but it's stopping the tests from running.

**Comment by huebnerr** [comment]
Agree that it looks like the install_vertica.sh script it suddenly failing. It was working a few days ago. @siting do you think the image file is missing from AWS? Considering it's 9.1.1, maybe it's been removed in favor of something else?

**Comment by sitingren** [comment]
I apologize for the inconvenience. The Vertica server version for CI tests has been updated from 9.1.1 to 9.3.1. I have updated the setting and Travis CI can now run successfully.

**Comment by mlh758** [comment]
@sitingren Thank you for fixing that. Looks like the tests passed this time.

**Comment by huebnerr** [comment]
I've done a second review and am happy with it.

**Comment by mlh758** [comment]
Thanks for getting this reviewed and merged in a timely manner. That can be a common issue with open source projects.

**Pull request merged**
