### PR TITLE
Reduce allocations in recvMessage() by re-using a buffer

### PR DESCRIPTION
**Pull request by fbernier**
This is working but I am opening it to get feedback as I have not yet measured anything. The goal is to reduce allocations in hot paths by re-using a buffer.

Hopefully I will have time to do some measurements soon.

### CODE REVIEW

**Comment by fbernier** [comment]
I added some small changes along with some hackish benchmark machinery that I think should be added in another PR, in case you ever want to keep them.

I had to work around the fact that the master branch has no benchmark defined so I had to pull in the `driver_test.go` file to it in order to make the comparison. I only reproduced the `BasicQuery` test and benchmarked it. In theory, the larger the result and the bigger the improvements would be. Here are the results:

```
benchmark                 old ns/op     new ns/op     delta
BenchmarkBasicQuery-2     9201026       9093504       -1.17%

benchmark                 old allocs     new allocs     delta
BenchmarkBasicQuery-2     176            153            -13.07%

benchmark                 old bytes     new bytes     delta
BenchmarkBasicQuery-2     6881          6331          -7.99%
```

**Comment by huebnerr** [comment]
@fbernier, is this ready to be merged?

**Comment by fbernier** [comment]
There are some more things I am looking at but I think this is a good first step that could be merged in yes. I would not the travis changes and benchcmp script though. We could merge only the benchmark, although feel free to improve it, and add benchcmp in another PR where I can get rid of the driver_test.go checkout. I can take care of cleaning this up later if you want.

**Comment by fbernier** [comment]
Finally I think this is ready as-is. Since it's in a post-hook the benchmarks can never make a build fail anyway. There could be some cleanups to do in the future but having this in as-in right now sounds fine to me.

**Comment by fbernier** [comment]
@huebnerr I removed the benchmark as I currently don't have a clean way of having them in but I might revisit later. This is ready to merge IMO.

**Comment by huebnerr** [comment]
OK. Will merge in once test pass.

**Pull request merged**
