### PR TITLE
Rollback severity seems to end the connection

### LINKED ISSUE #48: Hang when creating an already existing table inside transaction.
I have an endpoint that is creating a temporary table inside a transaction. That create table statement didn't have `IF NOT EXIST` and since go sql re-uses connections, I would often fall on a connection that already had this table.

When that was the case, it would just hang on the create table. I ended up figuring out what the problem was when I saw this when stracing the process.

```
[pid 129981] read(6, "SROLLBACK\0C42710\0V4213\0MObject \"temp_ids\" already exists\0F/data/qb_workspaces/jenkins2/ReleaseBuilds/Grader/REL-9_2_0-x_grader/build/vertica/Commands/DDL.cpp\0L2
2038\0RoutputAlreadyExistsEreport\0\0", 196) = 196
```

I am probably going to make a PR with a failing test when I have time.

### LINKED ISSUE #61: Driver hangs if user lacks permission for operation
Version: github.com/vertica/vertica-sql-go v0.1.7

```
timeout, cancel := context.WithTimeout(context.Background(), 30*time.Second)
defer cancel()
_, execErr := connection.ExecContext(timeout, view_sql_string)
```

If the user does not have permission to do the operation, in our case it was `CREATE OR REPLACE VIEW`, the driver will hang even with a timeout context passed in. The same sql passed into something like DBeaver errors out right away.

This seems similar to #48 although we aren't using a transaction.

Edit: This seems to happen for any DDL statement that returns an error. Dropping a table that does not exist can also trigger this.

### PR DESCRIPTION
**Pull request by mlh758**
Check for ROLLBACK severity and
guard against it in Close

Fixes #61
Fixes #48

Most of the changes in `Close` are white space, I swapped the if check to a if-return guard and then un-indented the body of it.

### CODE REVIEW

**Comment by mlh758** [comment]
It looks like something about the session reset logic in the last PR has caused this to no longer be a fix, the test I wrote causes the hang again. Need to figure out what is killing it.

**Comment by mlh758** [comment]
Problem was that ResetSession called Ping which would eventually wait on a message. If a ROLLBACK severity happens Vertica doesn't just ignore the close for the statement it ignores everything apparently. The ping would go unanswered, never complete, and the mutex in the sql package would never get released.

I added a dead flag on connection as well to signal when this happens and skip the Ping in ResetSession, the connection is definitely bad at this point and needs to get replaced.

**Comment by mlh758** [comment]
Hi, just wanted to follow up on this one and see if there's anything that needs changing.

**Comment by fbernier** [comment]
Looks good to me!

**Comment by huebnerr** [comment]
@mlh758 I need to do another code pass on it and re-update the branch. Been travelling a lot lately and haven't had the time to dig in too deeply into it. After today things SHOULD (tm) clear up a bit. Thanks for your patience.

**Comment by huebnerr** [comment]
Done and done. Looks good to me. Thanks again, @mlh758 !

**Comment by mlh758** [comment]
Thanks for reviewing and merging!

**Pull request merged**
